#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#rm -rf constant/polyMesh
#rm -rf ITHACAoutput
rm -rf ITHACAoutput/B*
rm -rf ITHACAoutput/E*
rm -rf ITHACAoutput/M*
rm -rf ITHACAoutput/P*
rm -rf ITHACAoutput/R*
rm -rf ITHACAoutput/r*
rm -rf ITHACAoutput/s*
rm -rf ITHACAoutput/U*
#rm -f log.*
#rm -rf 0.*
rm -f 0/Ulift*
rm -f 0/Plift*
